# Generated by Django 2.2.2 on 2019-06-14 10:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_auto_20190614_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbook',
            name='rental_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 14, 10, 9, 33, 698323, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returndate', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
