# Generated by Django 2.2.2 on 2019-06-18 08:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190614_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbook',
            name='rental_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 18, 8, 18, 37, 73465, tzinfo=utc)),
        ),
    ]
