# Generated by Django 2.2.2 on 2019-06-20 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190618_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbook',
            name='rental_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 20, 7, 20, 16, 923590, tzinfo=utc)),
        ),
    ]
